"""empty check

Revision ID: e442d449ffba
Revises: c7ee47a6526d
Create Date: 2025-05-24 20:13:01.497609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e442d449ffba'
down_revision: Union[str, None] = 'c7ee47a6526d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
 """Upgrade schema."""
 # ### commands auto generated by Alembic - please adjust! ###
 pass
 # ### end Alembic commands ###


def downgrade() -> None:
 """Downgrade schema."""
 # ### commands auto generated by Alembic - please adjust! ###
 pass
 # ### end Alembic commands ###
