"""
Configuration package initialization.
"""

from .app_config import Settings

settings = Settings()

SECRET_KEY = settings.SECRET_KEY
ALGORITHM = settings.ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = settings.ACCESS_TOKEN_EXPIRE_MINUTES
REFRESH_TOKEN_EXPIRE_MINUTES = settings.REFRESH_TOKEN_EXPIRE_MINUTES
OAUTH_CLIENT_ID = settings.OAUTH_CLIENT_ID
OAUTH_CLIENT_SECRET = settings.OAUTH_CLIENT_SECRET
OAUTH_SERVER_METADATA_URL = settings.OAUTH_SERVER_METADATA_URL
OAUTH_REDIRECT_URI = settings.OAUTH_REDIRECT_URI
OAUTH_SCOPE = settings.OAUTH_SCOPE

__all__ = [
    'configure_logging',
    'SECRET_KEY',
    'ALGORITHM',
    'ACCESS_TOKEN_EXPIRE_MINUTES',
    'REFRESH_TOKEN_EXPIRE_MINUTES',
    'OAUTH_CLIENT_ID',
    'OAUTH_CLIENT_SECRET',
    'OAUTH_SERVER_METADATA_URL',
    'OAUTH_REDIRECT_URI',
    'OAUTH_SCOPE',
]
