repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: []
        files: ^backend/

  - repo: local
    hooks:
      - id: npm-lint
        name: Lint frontend with ESLint
        entry: npm run lint --prefix frontend
        language: system
        pass_filenames: false

      - id: frontend-type-check
        name: Type-check frontend
        entry: npm run type-check --prefix frontend
        language: system
        pass_filenames: false
        files: ^frontend/
        types: [javascript, jsx, ts, tsx]

      - id: npm-test
        name: Run frontend tests
        entry: npm test --prefix frontend
        language: system
        pass_filenames: false

      - id: frontend-format
        name: Format frontend with Prettier
        entry: npm run format
        language: system
        pass_filenames: false
        files: ^frontend/
        types: [javascript, jsx, ts, tsx, json, css, markdown]

      - id: lint-staged
        name: Lint staged files
        entry: npx lint-staged
        language: system
        pass_filenames: false