repos:
  - repo: local
    hooks:
      - id: frontend-format
        name: Format frontend with Prettier
        entry: npm run format
        language: system
        pass_filenames: false
        files: ^frontend/
        types: [javascript, jsx, ts, tsx, json, css, markdown]
