/* eslint-disable */
// This file is auto-generated by scripts/generate_ts_enums.py

export enum TaskStatus {
  TO_DO = 'To Do',
  IN_PROGRESS = 'In Progress',
  IN_REVIEW = 'In Review',
  COMPLETED = 'Completed',
  BLOCKED = 'Blocked',
  CANCELLED = 'Cancelled',
  CONTEXT_ACQUIRED = 'Context Acquired',
  PLANNING_COMPLETE = 'Planning Complete',
  EXECUTION_IN_PROGRESS = 'Execution In Progress',
  PENDING_VERIFICATION = 'Pending Verification',
  VERIFICATION_COMPLETE = 'Verification Complete',
  VERIFICATION_FAILED = 'Verification Failed',
  COMPLETED_AWAITING_PROJECT_MANAGER = 'Completed Awaiting Project Manager',
  COMPLETED_HANDOFF = 'Completed Handoff',
  FAILED = 'Failed',
  IN_PROGRESS_AWAITING_SUBTASK = 'In Progress Awaiting Subtask',
  PENDING_RECOVERY_ATTEMPT = 'Pending Recovery Attempt',
}

export enum ActionType {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  LOGIN = 'login',
  LOGOUT = 'logout',
  ASSIGN = 'assign',
  COMPLETE = 'complete',
}

