"""add_timestamps_to_agents_table

Revision ID: a30db8a4b419
Revises: f838fc5b702d
Create Date: 2024-08-16 14:49:23.783752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30db8a4b419'
down_revision: Union[str, None] = 'f838fc5b702d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('agents', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now())) # Assuming created_at exists
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'updated_at')
    # op.drop_column('agents', 'created_at') # Assuming created_at is handled by an earlier migration
    # ### end Alembic commands ###
